import { NextRequest } from "next/server";
import { adminDb } from "@/lib/firebase-admin";
import { verifyAuth, unauthorizedResponse, forbiddenResponse } from "@/lib/auth";
import { isSuperAdmin } from "@/lib/admin";

const tours = [
  {
    id: "luxury-classic-sri-lanka",
    name: "Luxury Holidays Classic Sri Lanka",
    duration: { days: 16, nights: 15 },
    summary: "This itinerary takes in the very best that Sri Lanka has to offer. Journey from bustling Colombo to ancient ruins and temples of the Cultural Triangle, up into the mystical Hill Country full of tea plantations, then head down south to the coast for whale watching, surfing, and incredible food. Cap off a wonderful holiday in the UNESCO World Heritage site of Galle Fort.",
    route: ["Negombo", "Anuradhapura", "Sigiriya", "Kandy", "Tea Country", "Yala", "Galle"],
    tags: ["culture", "wildlife", "nature", "beach", "heritage"],
    heroImage: "/images/tours/luxury-classic/sigiriya.jpg",
    highlights: [
      "Explore magnificent Anuradhapura ancient city",
      "Climb UNESCO-listed Sigiriya Rock Fortress",
      "Visit Temple of the Tooth in Kandy",
      "Scenic train ride through Tea Country",
      "Safari at Yala National Park",
      "Discover UNESCO Galle Fort",
      "Visit Handunugoda Tea Estate",
      "Whale watching in Galle",
    ],
    placesToStay: [
      { location: "Negombo", hotel: "The Wallawwa", type: "Boutique Manor", image: "/images/hotels/walawwa-hotel.jpg" },
      { location: "Anuradhapura", hotel: "Ulagalla Resort", type: "Eco Boutique", image: "/images/hotels/ulagalla-resort.png" },
      { location: "Kandy", hotel: "The Kandy House", type: "Heritage Boutique", image: "/images/hotels/kandy-house.jpg" },
      { location: "Tea Country", hotel: "Ceylon Tea Trails", type: "Planter Bungalows", image: "/images/hotels/ceylon-tea-trails.png" },
      { location: "Yala", hotel: "Ruhunu Yala Safari Camping", type: "Luxury Camp", image: "/images/hotels/ruhunu-yala-safari.jpg" },
      { location: "Galle", hotel: "Kahanda Kanda", type: "Boutique Villa", image: "/images/hotels/kahanda-kanda.webp" },
    ],
    itinerary: [
      {
        day: 1,
        title: "Arrival",
        description: "Upon arrival, you will be greeted warmly by your own chauffeur and transferred from the Colombo International Airport to your hotel, The Wallawwa. Set in an expansive tropical garden, this former manor house indulges guests with its chic collection of guestrooms, gourmet cuisine, discreet service and decadent spa. You will have the remainder of the day at leisure to explore the surroundings or just relax.",
        image: "/images/tours/luxury-classic/negombo.jpg",
        location: "Negombo",
        activities: ["Airport pickup", "Hotel check-in", "Leisure time"],
        accommodation: "The Wallawwa",
      },
      {
        day: 2,
        title: "Negombo to Anuradhapura",
        description: "This morning, meet your personal driver and start your journey to Anuradhapura, approximately 4.5 hours away. Upon arrival, check into Ulagalla Resort. This perfectly positioned boutique eco-hotel is in prime location to explore the Cultural Triangle of Sri Lanka. Beautifully furnished to the highest standard with state-of-the-art amenities, each room features a four-poster bed, plunge pool and terrace, as well as bicycles for guests to use.",
        image: "/images/tours/luxury-classic/negombo-to-anuradhapura.png",
        location: "Anuradhapura",
        activities: ["Scenic drive", "Resort check-in", "Pool relaxation"],
        accommodation: "Ulagalla Resort",
      },
      {
        day: 3,
        title: "Visit Anuradhapura",
        description: "After breakfast, visit the magnificent Anuradhapura with your expert guide. Sights include Jethawanaramaya, Twin Ponds, Samadhi statue, Moonstone, Abayagiriya, Rathnaprasadaya, Thuparamaya and Ruwanweliseya. If time permits, visit Mihinthale and Isurumuniya with your driver. In the afternoon, make your way to Dambulla, which houses the famed Royal Rock Temple.",
        image: "/images/tours/luxury-classic/anuradhapura.jpg",
        location: "Anuradhapura",
        activities: ["Ancient city tour", "Dambulla Cave Temple", "Cultural exploration"],
        accommodation: "Ulagalla Resort",
      },
      {
        day: 4,
        title: "Visit Sigiriya en route to Kandy",
        description: "Depart Ulagalla Resort for Kandy. En route, visit Sigiriya Rock Fortress, an ancient rock fortress and palace ruin in the heart of the Matale District. This UNESCO World Heritage Site was built in the 5th century AD by King Kasyapa as a fortress-palace. The tour takes approximately 3 hours. Enjoy lunch at Ena de Silva then continue to Kandy. Upon arrival, explore the Temple of the Tooth and enjoy a cultural show before checking into The Kandy House.",
        image: "/images/tours/luxury-classic/sigiriya.jpg",
        location: "Kandy",
        activities: ["Sigiriya Rock climb", "Ancient frescoes", "Temple of the Tooth", "Cultural show"],
        accommodation: "The Kandy House",
      },
      {
        day: 5,
        title: "Kandy",
        description: "Your guide will take you on a tour to explore Kandy at your own leisure. Kandy was the last capital of the Sri Lankan kings and is a UNESCO World Heritage Site. Visit the Temple of the Tooth which houses the relic of Buddha, witness a traditional Kandyan dance performance, and explore the Royal Botanic Gardens. You may also enjoy a game of golf at Victoria's scenic Golf & Country Club or visit Udawattakele sanctuary.",
        image: "/images/tours/luxury-classic/kandy.jpg",
        location: "Kandy",
        activities: ["Temple of the Tooth", "Royal Botanic Gardens", "Cultural dance show", "City stroll"],
        accommodation: "The Kandy House",
      },
      {
        day: 6,
        title: "Kandy to Tea Country",
        description: "Early morning, head by train to the Hill Country in central Sri Lanka. The train ride from Kandy to the heart of Sri Lanka's Tea Country is one of the most scenic train rides in Asia. As you meander out of Kandy, dense jungle opens into cloud forest, with undulating vistas of immaculate tea bush carpets in between. On arrival, you will be driven to Tea Trails where you will check in and have the rest of the day free at leisure.",
        image: "/images/tours/luxury-classic/tea-country.jpg",
        location: "Tea Country",
        activities: ["Scenic train ride", "Mountain views", "Resort check-in"],
        accommodation: "Ceylon Tea Trails",
      },
      {
        day: 7,
        title: "Tea Country",
        description: "Relax and explore the beauty of the Tea Country at your leisure. Optional activities include a private guided tour of a tea factory to learn about the process and sample different teas, mountain biking along trails with a picnic lunch, white water rafting at Kitulgala, visit to Nuwara Eliya (Little Scotland) with opportunity to play golf on one of the most scenic courses in the world, or scale Adam's Peak at sunrise.",
        image: "/images/tours/luxury-classic/tea-factory.jpg",
        location: "Tea Country",
        activities: ["Tea factory tour", "Tea tasting", "Optional hiking", "Mountain biking"],
        accommodation: "Ceylon Tea Trails",
      },
      {
        day: 8,
        title: "Tea Country",
        description: "Another day to enjoy the all-inclusive comforts of Tea Trails. Continue exploring the misty highlands, visit more tea estates, or simply relax and take in the stunning mountain scenery from your colonial planter's bungalow.",
        image: "/images/tours/luxury-classic/tea-factory-1.jpg",
        location: "Tea Country",
        activities: ["Leisure day", "Tea estate visits", "Relaxation"],
        accommodation: "Ceylon Tea Trails",
      },
      {
        day: 9,
        title: "Tea Trails to Yala",
        description: "Rise early for a 6-hour drive to Ruhunu Yala Safari tented camp in Yala National Park. Arrive at noon to be greeted by a gourmet lunch, followed by an evening game drive and dinner. Ruhunu Yala Safaris combines professional guides and luxury camping facilities with the ultimate safari experience deep in Yala National Park.",
        image: "/images/tours/luxury-classic/rawana-ella.jpg",
        location: "Yala",
        activities: ["Scenic drive", "Gourmet lunch", "Evening safari"],
        accommodation: "Ruhunu Yala Safari Camping",
      },
      {
        day: 10,
        title: "Yala Safari",
        description: "Full day of safari adventures in Yala National Park. Yala is home to the world's highest density of leopards, along with elephants, sloth bears, and exotic birds. Enjoy morning and evening game drives with expert guides, and relax at camp during the heat of the day.",
        image: "/images/tours/luxury-classic/yala-safari.jpg",
        location: "Yala",
        activities: ["Morning safari", "Wildlife spotting", "Evening safari"],
        accommodation: "Ruhunu Yala Safari Camping",
      },
      {
        day: 11,
        title: "Yala Safari",
        description: "Continue your safari experience with more game drives. The diverse landscapes of Yala offer excellent opportunities to spot leopards, elephants, crocodiles, and over 200 species of birds. Enjoy bush dinners under the stars.",
        image: "/images/tours/luxury-classic/yala-safari-kotiya.jpg",
        location: "Yala",
        activities: ["Safari drives", "Bird watching", "Bush dinner"],
        accommodation: "Ruhunu Yala Safari Camping",
      },
      {
        day: 12,
        title: "Yala Safari",
        description: "Final morning safari to catch wildlife at their most active before departing from camp. A magical once-in-a-lifetime camping experience at the edge of Sri Lanka's premier game reserve.",
        image: "/images/tours/luxury-classic/yala-safari-wadura.jpg",
        location: "Yala",
        activities: ["Dawn safari", "Wildlife photography", "Camp departure"],
        accommodation: "Ruhunu Yala Safari Camping",
      },
      {
        day: 13,
        title: "From Yala to Galle",
        description: "Drive to Galle, approximately 6 hours away. Upon arrival, check into Kahanda Kanda, followed by lunch and a tour of a cinnamon plantation. In the afternoon, visit Handunugoda Tea Estate, possibly the closest tea plantation in the world to the sea. Known as the Virgin's White Tea Factory, it produces tea completely untouched by hand. Finish with a tea tasting.",
        image: "/images/tours/luxury-classic/matara.jpg",
        location: "Galle",
        activities: ["Coastal drive", "Cinnamon plantation", "Handunugoda Tea Estate", "Tea tasting"],
        accommodation: "Kahanda Kanda",
      },
      {
        day: 14,
        title: "Exploring Galle",
        description: "Free day at leisure to relax and enjoy Kahanda Kanda and Galle. Just 15 minutes from the beaches of Galle. Suggested activities include visiting the UNESCO World Heritage Site of Galle Fort, exploring boutique shops on Hospital Street, Church Street or Leyn Bann Street, or taking a Galle Fort walk excursion with your chauffeur.",
        image: "/images/tours/luxury-classic/galle-fort.jpg",
        location: "Galle",
        activities: ["Galle Fort tour", "Boutique shopping", "Beach time"],
        accommodation: "Kahanda Kanda",
      },
      {
        day: 15,
        title: "Exploring Galle",
        description: "Another day to explore the southern coast. Visit Unawatuna Beach, a turtle hatchery, take a rainforest excursion, enjoy a boat ride on Koggala Lake, or go whale watching. Spend your final night at Kahanda Kanda and prepare for departure.",
        image: "/images/tours/luxury-classic/galle.png",
        location: "Galle",
        activities: ["Beach visit", "Turtle hatchery", "Whale watching", "Koggala Lake boat ride"],
        accommodation: "Kahanda Kanda",
      },
      {
        day: 16,
        title: "Departure",
        description: "Around 8:00 am you will be picked up at your hotel and driven to Colombo airport (approximately 3 hour drive) in time to catch your flight home.",
        image: "/images/tours/luxury-classic/colombo.jpeg",
        location: "Colombo Airport",
        activities: ["Airport transfer", "Departure"],
      },
    ],
  },
  {
    id: "luxury-wild-holidays",
    name: "Luxury Wild Holidays Sri Lanka",
    duration: { days: 14, nights: 13 },
    summary: "Renowned for its charming colonial vibe, incredible tea country and plethora of beaches, Sri Lanka is also home to some great wilderness. During this itinerary, immerse yourself in the country and encounter exotic animals that call the Pearl of the Indian Ocean home. From elephants to whales, the ever elusive leopard and bears, there is much to be admired.",
    route: ["Negombo", "Kandy", "Koslanda", "Yala", "Koggala", "Galle"],
    tags: ["wildlife", "nature", "safari", "beach"],
    heroImage: "/images/tours/luxury-wild/leopard-tree.jpg",
    highlights: [
      "Millennium Elephant Foundation experience",
      "Temple of the Tooth in Kandy",
      "Royal Botanical Gardens",
      "Living Heritage Koslanda retreat",
      "Yala National Park safari camping",
      "Leopard and elephant spotting",
      "Koggala Lake exploration",
      "Galle Fort discovery",
    ],
    placesToStay: [
      { location: "Negombo", hotel: "The Wallawwa", type: "Boutique Manor", image: "/images/hotels/walawwa.jpg" },
      { location: "Kandy", hotel: "Polwaththa Eco Lodges", type: "Eco Lodge", image: "/images/hotels/polawaththa.jpg" },
      { location: "Koslanda", hotel: "Living Heritage Koslanda", type: "Boutique Hotel", image: "/images/hotels/living-heritage.jpg" },
      { location: "Yala", hotel: "Ruhunu Safari Camping", type: "Luxury Camp", image: "/images/hotels/ruhunu-safari.jpg" },
      { location: "Koggala", hotel: "Tri Lanka", type: "Sustainable Luxury", image: "/images/hotels/tri-lanka.jpg" },
    ],
    itinerary: [
      { day: 1, title: "Arrival", description: "Upon arrival, you will be greeted warmly by your own chauffeur and transferred from the Colombo International Airport to The Wallawwa. Set in an expansive tropical garden, this former manor house indulges guests with its chic collection of guestrooms, gourmet cuisine, discreet service and decadent spa. Remainder of the day at leisure.", image: "/images/tours/luxury-wild/negombo.jpg", location: "Negombo", activities: ["Airport pickup", "Hotel check-in", "Leisure time"], accommodation: "The Wallawwa" },
      { day: 2, title: "From Negombo to Kandy", description: "Travel into the hills via the Millennium Elephant Foundation where you can enjoy watching elephants bathing in a river. Continue to Polwaththa Eco Lodges, consisting of 14 lodges in a pristine environment, giving you a \"Living-in-the-Jungle\" experience. Situated 19km east of Kandy, each lodge offers comfort with great views and privacy, within reach of the stunning Knuckles Range.", image: "/images/tours/luxury-wild/millennium-elephant.jpeg", location: "Kandy", activities: ["Millennium Elephant Foundation", "Elephant watching", "Eco lodge check-in"], accommodation: "Polwaththa Eco Lodges" },
      { day: 3, title: "Kandy Exploration", description: "Explore Kandy at your leisure. Suggested activities include hiking at the Hantane Range, admiring Temple of the Tooth (Sri Lanka's most sacred shrine), visiting the Royal Botanical Gardens and a tea museum, and watching a cultural dancing show featuring traditional Kandyan dance accompanied by live music.", image: "/images/tours/luxury-wild/temple-of-tooth.jpeg", location: "Kandy", activities: ["Temple of the Tooth", "Royal Botanical Gardens", "Cultural dance show", "Hiking"], accommodation: "Polwaththa Eco Lodges" },
      { day: 4, title: "From Kandy to Koslanda", description: "Travel south from Kandy into Sri Lanka's vertiginous Tea Country, named for the velveteen tea plantations that carpet the misty hills. Drive through the market town of Nuwara Eliya, and continue to Koslanda, near Haputale, to stay at Living Heritage Koslanda. This secluded boutique hotel celebrates Sri Lanka's traditional architectural design and is set in 80 acres, including a patch of forest known locally as \"God's Forest\", with a river and secluded waterfall.", image: "/images/tours/luxury-wild/kandy-to-koslanda.jpg", location: "Koslanda", activities: ["Scenic drive", "Tea country views", "Boutique hotel check-in"], accommodation: "Living Heritage Koslanda" },
      { day: 5, title: "Koslanda", description: "Elephants seasonally travel through the forest and much wildlife can be seen in the hotel grounds. Suggested activities include guided walks, visits to tea and rubber plantations, and day trips to Udawalawe National Park, famous for herds of elephants.", image: "/images/tours/luxury-wild/koslanda.jpg", location: "Koslanda", activities: ["Guided forest walks", "Tea plantation visits", "Wildlife spotting"], accommodation: "Living Heritage Koslanda" },
      { day: 6, title: "Admiring Wildlife at Yala National Park", description: "Descend the hills into the low-lying southeastern plains and to the edge of Yala National Park, stopping off en route at Buduruwagala – a series of seven well-preserved Buddhist figures carved into sheer rock. Yala National Park is the island's premier game reserve, home to a dense population of leopards, elephants and sloth bears.", image: "/images/tours/luxury-wild/buduruwagala.jpg", location: "Yala", activities: ["Buduruwagala Buddhist carvings", "Camp check-in", "Evening safari"], accommodation: "Ruhunu Safari Camping" },
      { day: 7, title: "Yala Safari", description: "Camping at the edge of the park is a magical once-in-a-lifetime experience. Ruhunu Yala Safari Camp has comfortable family and double tents, with two game drives per day led by experienced local guides. Search for leopards, elephants, and the incredible diversity of wildlife in this premier game reserve.", image: "/images/tours/luxury-wild/yala-1.jpg", location: "Yala", activities: ["Morning safari", "Leopard spotting", "Evening safari"], accommodation: "Ruhunu Safari Camping" },
      { day: 8, title: "Yala Safari", description: "Continue your safari adventure with more game drives through Yala's diverse landscapes. The park is home to over 200 bird species, making it a paradise for bird watchers as well as those seeking larger wildlife encounters.", image: "/images/tours/luxury-wild/yala-2.jpg", location: "Yala", activities: ["Safari drives", "Bird watching", "Wildlife photography"], accommodation: "Ruhunu Safari Camping" },
      { day: 9, title: "Koggala Lake", description: "Travel west along the picturesque cove-sprinkled southern coastline to Koggala Lake, a 30-minute drive from the famed UNESCO town of Galle. Stay at Tri Lanka, a fantastic hotel celebrating local materials and luxurious yet fully sustainable architectural design on the banks of Koggala Lake, one of Sri Lanka's largest inland waterways.", image: "/images/tours/luxury-wild/koggala.jpg", location: "Koggala", activities: ["Coastal drive", "Sustainable luxury hotel", "Lake views"], accommodation: "Tri Lanka" },
      { day: 10, title: "Koggala", description: "Take a boat trip on Koggala Lake to see birds, visit Sinharaja Rainforest, go whale or dolphin watching (in season) or simply relax on a nearby beach. Other suggested activities include guided bicycle rides, river kayaking, surfing and visits to local turtle hatcheries.", image: "/images/tours/luxury-wild/sinharaja.jpg", location: "Koggala", activities: ["Lake boat trip", "Bird watching", "Beach relaxation"], accommodation: "Tri Lanka" },
      { day: 11, title: "Koggala", description: "Another day to explore the area around Koggala Lake. Visit the Sinharaja Rainforest, a UNESCO World Heritage Site, or spend the day kayaking, cycling, or relaxing at the sustainable luxury of Tri Lanka.", image: "/images/tours/luxury-wild/cycling.jpg", location: "Koggala", activities: ["Rainforest visit", "Kayaking", "Cycling"], accommodation: "Tri Lanka" },
      { day: 12, title: "Koggala", description: "Continue to enjoy the peaceful surroundings of Koggala Lake. Optional whale watching excursions, visits to turtle hatcheries, or simply relaxing by the pool with views of the lake.", image: "/images/tours/luxury-wild/koggala-2.jpg", location: "Koggala", activities: ["Whale watching", "Turtle hatchery", "Pool relaxation"], accommodation: "Tri Lanka" },
      { day: 13, title: "Koggala", description: "Final full day to explore Galle Fort or enjoy the beaches. The UNESCO World Heritage Site of Galle Fort is just a short drive away, offering boutique shops, art galleries, and historic ramparts to explore.", image: "/images/tours/luxury-wild/galle-fort.jpeg", location: "Koggala", activities: ["Galle Fort visit", "Shopping", "Beach time"], accommodation: "Tri Lanka" },
      { day: 14, title: "Departure", description: "Depart Galle and transfer to Colombo Airport for your return flight home. Visit Galle Dutch Fort and Sea Turtle Hatchery en route to the airport.", image: "/images/tours/luxury-wild/turtles.jpg", location: "Colombo Airport", activities: ["Galle Fort visit", "Turtle hatchery", "Airport transfer"] },
    ],
  },
  {
    id: "luxury-honeymoon",
    name: "Luxury Honeymoon in Sri Lanka",
    duration: { days: 14, nights: 13 },
    summary: "Sri Lanka makes a perfect destination for newlyweds. Famed for its wonderful landscape and relaxing atmosphere, it's such a romantic place. There are romantic spots all over the island, simply perfect for a honeymoon. Visit a variety of romantic settings such as the misty tea plantations, historical sites and Yala National Park, while staying at the most romantic hotels.",
    route: ["Negombo", "Kandy", "Koslanda", "Yala", "Mirissa", "Galle"],
    tags: ["honeymoon", "romance", "luxury", "beach", "wildlife"],
    heroImage: "/images/tours/honeymoon/mirissa.jpg",
    highlights: [
      "Romantic manor house stay at The Wallawwa",
      "Millennium Elephant Foundation experience",
      "Historic Kandy House boutique stay",
      "Secluded Living Heritage Koslanda",
      "Romantic safari camping at Yala",
      "Beachfront bliss in Mirissa",
      "Whale watching excursion",
      "Galle Fort exploration",
    ],
    placesToStay: [
      { location: "Negombo", hotel: "The Wallawwa", type: "Boutique Manor", image: "/images/hotels/walawwa-hotel-pkg3.jpg" },
      { location: "Kandy", hotel: "The Kandy House", type: "Heritage Boutique", image: "/images/hotels/kandy-house-pkg3.jpg" },
      { location: "Koslanda", hotel: "Living Heritage Koslanda", type: "Boutique Hotel", image: "/images/hotels/living-heritage-koslanda-pkg3.webp" },
      { location: "Yala", hotel: "Ruhunu Safari Camping", type: "Honeymoon Suite", image: "/images/hotels/ruhunu-yala-safari-pkg3.jpg" },
      { location: "Mirissa", hotel: "Lantern Boutique Hotel", type: "Beachfront Boutique", image: "/images/hotels/lantern-boutique-hotel.jpg" },
    ],
    itinerary: [
      { day: 1, title: "Arrival", description: "Upon arrival, you will be greeted warmly by your own chauffeur and transferred from the Colombo International Airport to The Wallawwa. Set in an expansive tropical garden, this former manor house indulges couples with its chic collection of guestrooms, gourmet cuisine, discreet service and decadent spa – the venue for post- and pre-flight pampering.", image: "/images/tours/honeymoon/arrival.jpg", location: "Negombo", activities: ["Airport pickup", "Romantic check-in", "Spa relaxation"], accommodation: "The Wallawwa" },
      { day: 2, title: "Negombo", description: "Spend the day at leisure to explore the surroundings or just relax. Enjoy the tropical gardens, indulge in couples spa treatments, and savor gourmet cuisine at this romantic manor house.", image: "/images/tours/honeymoon/negombo.jpg", location: "Negombo", activities: ["Couples spa", "Garden strolls", "Romantic dinner"], accommodation: "The Wallawwa" },
      { day: 3, title: "Exploring Kandy", description: "Travel to your next destination, Kandy – \"City Top of the Mountain\". On the way, visit the Millennium Elephant Foundation to observe and walk with elephants. Arrive at the charming and historic Kandy House, a stunning manor house that is beautifully romantic and particularly suited to honeymooners.", image: "/images/tours/honeymoon/exploring-kandy.jpg", location: "Kandy", activities: ["Elephant experience", "Scenic drive", "Romantic hotel check-in"], accommodation: "The Kandy House" },
      { day: 4, title: "Kandy", description: "Explore Kandy at your leisure. Suggested activities include hiking at the Hantane Range, admiring Temple of the Tooth (Sri Lanka's most sacred shrine), visiting the Royal Botanical Gardens and a tea museum, and enjoying a traditional Kandyan dance show.", image: "/images/tours/honeymoon/kandy.jpg", location: "Kandy", activities: ["Temple of the Tooth", "Botanical Gardens", "Cultural show"], accommodation: "The Kandy House" },
      { day: 5, title: "From Kandy to Koslanda", description: "Travel south from Kandy into Sri Lanka's vertiginous Tea Country. Drive through the market town of Nuwara Eliya and continue to Koslanda to stay at Living Heritage Koslanda. This secluded boutique hotel offers three hugely spacious suites with generous living areas, courtyard with alfresco jacuzzi and open-to-the-skies shower.", image: "/images/tours/honeymoon/kandy-to-koslanda.jpg", location: "Koslanda", activities: ["Tea country drive", "Boutique hotel", "Jacuzzi relaxation"], accommodation: "Living Heritage Koslanda" },
      { day: 6, title: "Koslanda", description: "Set in 80 acres, the property borders a patch of forest known locally as \"God's Forest\", which contains a river and a secluded waterfall. Suggested activities include trekking, tree planting and cooking classes together.", image: "/images/tours/honeymoon/koslanda.jpg", location: "Koslanda", activities: ["Waterfall visit", "Couples cooking class", "Forest trekking"], accommodation: "Living Heritage Koslanda" },
      { day: 7, title: "Yala National Park", description: "Travel from the hills into the low-lying southeastern plains to the edge of Yala National Park. Stop at Buduruwagala, a series of seven well-preserved Buddhist figures carved into sheer rock. Yala National Park is the island's premier game reserve, home to leopards, elephants and sloth bears.", image: "/images/tours/honeymoon/yala-national-park.jpg", location: "Yala", activities: ["Buddhist rock carvings", "Safari camp arrival", "Evening safari"], accommodation: "Ruhunu Safari Camping" },
      { day: 8, title: "Yala Safari", description: "Cozy up under canvas in the camp's beautifully secluded AC Honeymoon Suite, dine à deux by candlelight, shower under the stars and enjoy expertly guided game drives into the park. A magical once-in-a-lifetime experience for couples.", image: "/images/tours/honeymoon/yala-safari-1.jpg", location: "Yala", activities: ["Game drives", "Romantic candlelit dinner", "Star gazing"], accommodation: "Ruhunu Safari Camping" },
      { day: 9, title: "Yala Safari", description: "Continue your romantic safari adventure. Search for the elusive leopard together, spot elephants at waterholes, and enjoy the thrill of African-style safari in this incredible national park.", image: "/images/tours/honeymoon/yala-safari-2.jpg", location: "Yala", activities: ["Morning safari", "Wildlife spotting", "Sunset drinks"], accommodation: "Ruhunu Safari Camping" },
      { day: 10, title: "Mirissa", description: "Travel west along the picturesque cove-sprinkled southern coastline to Mirissa, famed for pretty beaches and surfing lessons. Check into Lantern Boutique Hotel, a blissful beach villa with swimming pool overlooking the Indian Ocean.", image: "/images/tours/honeymoon/mirissa.jpg", location: "Mirissa", activities: ["Coastal drive", "Beach check-in", "Sunset on beach"], accommodation: "Lantern Boutique Hotel" },
      { day: 11, title: "Mirissa", description: "Enjoy alfresco dining, relax poolside, indulge in spa treatments together. Optional whale watching trip to see blue whales and dolphins, or take a city tour of Matara.", image: "/images/tours/honeymoon/mirissa-2.jpg", location: "Mirissa", activities: ["Whale watching", "Couples spa", "Poolside relaxation"], accommodation: "Lantern Boutique Hotel" },
      { day: 12, title: "Mirissa", description: "Another day of beachfront bliss. Surfing lessons, sunset walks along the beach, or simply enjoying the romantic atmosphere of this beautiful southern coast.", image: "/images/tours/honeymoon/mirissa-3.jpg", location: "Mirissa", activities: ["Surfing lessons", "Beach walks", "Romantic dinner"], accommodation: "Lantern Boutique Hotel" },
      { day: 13, title: "Mirissa", description: "Final full day to enjoy the paradise beaches of Mirissa. Snorkeling, paddleboarding, or simply lounging on the golden sand before your journey home tomorrow.", image: "/images/tours/honeymoon/mirissa-4.jpg", location: "Mirissa", activities: ["Snorkeling", "Beach relaxation", "Farewell dinner"], accommodation: "Lantern Boutique Hotel" },
      { day: 14, title: "Departure", description: "Depart Mirissa and transfer to Colombo Airport for your return flight home. Visit Galle Dutch Fort and Sea Turtle Hatchery en route to the airport.", image: "/images/tours/honeymoon/departure.webp", location: "Colombo Airport", activities: ["Galle Fort visit", "Turtle hatchery", "Airport transfer"] },
    ],
  },
  {
    id: "discover-luxury-secret",
    name: "Discover Luxury Secret Sri Lanka",
    duration: { days: 10, nights: 9 },
    summary: "On this 10-day trip, discover the hidden side to the exotic island of Sri Lanka. Travel west to east from the wildlife of Wilpattu, through the ancient culture of Sigiriya and onto the palm-fringed beaches of Pasikuda. Far from the crowds to the south, this promises to be a trip where you can relax and discover in equal measure.",
    route: ["Negombo", "Wilpattu", "Sigiriya", "Pasikuda", "Negombo"],
    tags: ["wildlife", "culture", "beach", "off-the-beaten-path"],
    heroImage: "/images/tours/luxury-secret/sigiriya-sunset.jpg",
    highlights: [
      "Wilpattu National Park – real leopard country",
      "Luxury Leopard Trails safari camp",
      "Sigiriya Rock Fortress climb",
      "Ancient wall paintings discovery",
      "Pristine Pasikuda beaches",
      "Ayurvedic spa treatments",
      "Boutique manor house stays",
      "Off-the-beaten-path exploration",
    ],
    placesToStay: [
      { location: "Negombo", hotel: "The Wallawwa", type: "Boutique Manor" },
      { location: "Wilpattu", hotel: "Leopard Trails Camp", type: "Luxury Safari Camp" },
      { location: "Sigiriya", hotel: "Water Garden Sigiriya", type: "Boutique Resort" },
      { location: "Pasikuda", hotel: "Uga Bay Resort", type: "Beach Resort" },
    ],
    itinerary: [
      { day: 1, title: "Arrival", description: "Upon arrival, you will be greeted warmly by your own chauffeur and transferred from the Colombo International Airport to The Wallawwa. Set in an expansive tropical garden, this former manor house indulges guests with its chic collection of guestrooms, gourmet cuisine, discreet service and decadent spa.", image: "/images/tours/luxury-secret/kalpitiya-beach-sunset.jpg", location: "Negombo", activities: ["Airport pickup", "Manor house check-in", "Leisure time"], accommodation: "The Wallawwa" },
      { day: 2, title: "Wilpattu", description: "Begin your journey north to Wilpattu National Park. Forget the bustling plains of Yala, for Wilpattu is real leopard country. Spend your nights at the luxurious Leopard Trails camp, fully immersed in the wildlife that surrounds you. Bounded by rivers and peppered with large lakes known as \"villus\", Wilpattu provides the perfect setting for spotting game.", image: "/images/tours/luxury-secret/leopard-tree.jpg", location: "Wilpattu", activities: ["Safari drive", "Leopard spotting", "Luxury camp dinner"], accommodation: "Leopard Trails Camp" },
      { day: 3, title: "Wilpattu Safari", description: "Keep your eyes peeled for sloth bears, barking deer and Asian elephants. Join expert guides as you head out onto the plains in search of fauna – but also listen as they unveil the great archaeological and historical importance of the park. Wildlife, history, and tantalizing Sri Lankan cuisine served around a campfire.", image: "/images/tours/luxury-secret/elephants-herd.jpg", location: "Wilpattu", activities: ["Game drives", "Wildlife spotting", "Campfire dinner"], accommodation: "Leopard Trails Camp" },
      { day: 4, title: "Sigiriya", description: "Continue east to the foot of Sri Lanka's Cultural Triangle – Sigiriya. Stay at the beautiful Water Garden Sigiriya, a peaceful retreat set amid landscaped gardens with stunning views onto Sigiriya's star attraction. Dust off each day with a dip in the pool, a massage at the spa and a moonlit gourmet dinner.", image: "/images/tours/luxury-secret/sigiriya-sunset.jpg", location: "Sigiriya", activities: ["Resort check-in", "Pool relaxation", "Spa treatment"], accommodation: "Water Garden Sigiriya" },
      { day: 5, title: "Sigiriya Rock", description: "Spend the day with a private guide visiting this ancient site. Climb your way to the top of Sigiriya Rock, past ancient wall paintings, to reach views that extend all the way into the horizon over dense jungle. A mythical past of feuding dynasties suits Sigiriya's striking setting – built in the 5th century AD by King Kasyapa as a fortress-palace.", image: "/images/tours/luxury-secret/sigiriya-sunset-2.jpg", location: "Sigiriya", activities: ["Sigiriya Rock climb", "Ancient frescoes", "Panoramic views"], accommodation: "Water Garden Sigiriya" },
      { day: 6, title: "Pasikuda", description: "A final drive east takes you to your coastal destination where you can relax at the stylish Uga Bay Resort. Oozing luxury and relaxation, it's beached-out bliss all the way here. Lie back on the perfect white sands and dip your feet into the warm Indian Ocean.", image: "/images/tours/luxury-secret/kalpitiya-beach-2.jpg", location: "Pasikuda", activities: ["Coastal drive", "Beach resort check-in", "Ocean swimming"], accommodation: "Uga Bay Resort" },
      { day: 7, title: "Pasikuda Beach", description: "Four nights stay means plenty of time to indulge in a local Ayurvedic massage where you can listen to the calming ocean waves within Uga Bay's beachfront spa. Relax on the pristine white sand beaches of the east coast.", image: "/images/tours/luxury-secret/snorkeling-reef.jpg", location: "Pasikuda", activities: ["Ayurvedic spa", "Beach relaxation", "Ocean activities"], accommodation: "Uga Bay Resort" },
      { day: 8, title: "Pasikuda Beach", description: "Continue to enjoy the pristine beaches of Pasikuda. Snorkeling, diving, or simply lounging by the pool with views of the Indian Ocean. This less-visited east coast offers a more peaceful beach experience.", image: "/images/tours/luxury-secret/kalpitiya-beach-3.jpg", location: "Pasikuda", activities: ["Snorkeling", "Pool relaxation", "Beach walks"], accommodation: "Uga Bay Resort" },
      { day: 9, title: "Negombo", description: "Before returning home, stopover in Negombo for a night at the hidden oasis of The Wallawwa. Here, enjoy your last few bites of the freshest fusion in Asian cuisine whilst overlooking exquisite gardens. Authentic and chic, the rooms offer a lovely last slice of luxury before departing.", image: "/images/tours/luxury-secret/kalpitiya-beach-4.jpg", location: "Negombo", activities: ["Scenic transfer", "Final dinner", "Garden relaxation"], accommodation: "The Wallawwa" },
      { day: 10, title: "Departure", description: "Morning you'll head to the airport for your flight home, taking with you memories of Sri Lanka's secret corners and hidden gems.", image: "/images/tours/luxury-secret/kalpitiya-beach-5.jpg", location: "Colombo Airport", activities: ["Airport transfer", "Departure"] },
    ],
  },
  {
    id: "tea-plantations-coastal",
    name: "Tea Plantations & Coastal Hideaways",
    duration: { days: 10, nights: 9 },
    summary: "A lush tropical island with nothing below it but the huge expanse of the Indian Ocean, Sri Lanka is a hive of energy. Visit fifth century fortresses, learn how tea is made and explore gorgeous beachfront villages, all while staying in some of our favorite hotels in the world. On this trip you'll be completely charmed by this little Asian nation.",
    route: ["Negombo", "Anuradhapura", "Kandy", "Tea Country", "Tangalle", "Galle"],
    tags: ["culture", "tea", "beach", "heritage"],
    heroImage: "/images/tours/tea-coastal/tea-country.jpg",
    highlights: [
      "Cultural Triangle exploration",
      "Elephant safari in Minneriya",
      "Ancient Buddhist caves of Dambulla",
      "Polonnaruwa historic city",
      "Temple of the Tooth in Kandy",
      "Scenic train through Tea Country",
      "White beaches of Tangalle",
      "UNESCO Galle Fort discovery",
    ],
    placesToStay: [
      { location: "Negombo", hotel: "The Wallawwa", type: "Boutique Manor", image: "/images/hotels/walawwa-hotel-pkg5.jpg" },
      { location: "Anuradhapura", hotel: "Ulagalla Resort", type: "Eco Boutique", image: "/images/hotels/ulagalla-resort-pkg5.png" },
      { location: "Kandy", hotel: "The Kandy House", type: "Heritage Boutique", image: "/images/hotels/kandy-house-pkg5.jpg" },
      { location: "Tea Country", hotel: "Ceylon Tea Trails", type: "Planter Bungalows", image: "/images/hotels/ceylon-tea-trails-pkg5.png" },
      { location: "Tangalle", hotel: "Anantara Peace Haven Resort", type: "Beach Resort", image: "/images/hotels/anantara-peace-haven.jpg" },
      { location: "Galle", hotel: "Amangalla", type: "Heritage Luxury", image: "/images/hotels/amangalla.webp" },
    ],
    itinerary: [
      { day: 1, title: "Arrival", description: "Upon arrival, you will be greeted warmly by your own chauffeur and transferred from the Colombo International Airport to The Wallawwa. Set in an expansive tropical garden, this former manor house indulges guests with its chic collection of guestrooms, gourmet cuisine, discreet service and decadent spa.", image: "/images/tours/tea-coastal/arrival.jpg", location: "Negombo", activities: ["Airport pickup", "Manor house check-in", "Leisure time"], accommodation: "The Wallawwa" },
      { day: 2, title: "Thirappane - Cultural Triangle", description: "Drive to the Cultural Triangle for three nights at the sun-drenched Ulagalla Resort – a retreat with thatched bungalows on stilts floating above paddy fields. By day, visit some of Sri Lanka's oldest historic monuments and unwind in your private plunge pool. With a wine cellar and lagoon for kayaking, you'll be immersed in the authentic beauty of this Sri Lankan gem.", image: "/images/tours/tea-coastal/thirappane.jpg", location: "Anuradhapura", activities: ["Scenic drive", "Resort check-in", "Private plunge pool"], accommodation: "Ulagalla Resort" },
      { day: 3, title: "Minneriya / Polonnaruwa", description: "Take an elephant safari in Minneriya, see the ancient Buddhist cave temples of Dambulla or explore the city of Polonnaruwa. This UNESCO World Heritage Site features ancient wall paintings and historical significance that brings Sri Lanka's rich history to life.", image: "/images/tours/tea-coastal/minneriya.webp", location: "Cultural Triangle", activities: ["Elephant safari", "Dambulla caves", "Polonnaruwa ruins"], accommodation: "Ulagalla Resort" },
      { day: 4, title: "Kandy", description: "Head to Kandy for a brief but memorable stop. Visit Buddha's Tooth Relic or explore the stunning Botanical Gardens, where Giant Java trees have branches so wide they need stilts to stay up. Relax by the pool at the romantic Kandy House sipping locally grown tea – quaint, colonial comfort at its best.", image: "/images/tours/tea-coastal/kandy.jpg", location: "Kandy", activities: ["Temple of the Tooth", "Botanical Gardens", "Tea tasting"], accommodation: "The Kandy House" },
      { day: 5, title: "Hatton - Tea Country", description: "No trip to Sri Lanka is complete without visiting tea country. Take a train (still run on British colonial equipment) through rolling fields of tea leaves and learn how tea is processed, before sampling the freshest cuppa of your life. Rest at Tea Trails – four old planter's bungalows now converted into a boutique hotel.", image: "/images/tours/tea-coastal/hatton.jpg", location: "Tea Country", activities: ["Scenic train ride", "Tea factory tour", "Tea tasting"], accommodation: "Ceylon Tea Trails" },
      { day: 6, title: "Tea Country", description: "Enjoy evening jazz cocktail hours, discuss the next day's personalized menu with the chef, and sleep under a mosquito net in your colonial style room. Pastoral perfection in the misty highlands of Sri Lanka.", image: "/images/tours/tea-coastal/tea-country.jpg", location: "Tea Country", activities: ["Tea estate walks", "Cocktail hours", "Colonial dining"], accommodation: "Ceylon Tea Trails" },
      { day: 7, title: "Tangalle", description: "Head to the white beaches of Tangalle for some coastline fun. Stroll along the shore, kite-surf, wakeboard, deep sea fish or simply indulge in the amazing Anantara Peace Haven hotel. Relax in your suite with uninterrupted views of the palm-studded beach.", image: "/images/tours/tea-coastal/tangalle.webp", location: "Tangalle", activities: ["Beach arrival", "Water sports", "Ocean views"], accommodation: "Anantara Peace Haven Resort" },
      { day: 8, title: "Tangalle", description: "Dine at the poolside restaurant overlooking golden sand beaches, perfect for reflecting on your Sri Lankan adventure. Time it right and experience both elephants in the north and blue whales in the south – nature's most graceful yet powerful creatures.", image: "/images/tours/tea-coastal/tangalle-1.jpg", location: "Tangalle", activities: ["Whale watching", "Beach relaxation", "Poolside dining"], accommodation: "Anantara Peace Haven Resort" },
      { day: 9, title: "Galle", description: "Transfer to the magical fortress town of Galle, filled with red-tiled rooftops over eclectic art galleries, cafes and boutique hotels. Visit local markets with the chef during a cookery lesson, or try delicious \"wade\" (street snacks) with the hotel's signature \"Arrack sour\". Unwind in Sri Lanka's most incredible spa before watching the sunset from Amangalla's top floor lounge.", image: "/images/tours/tea-coastal/galle.jpg", location: "Galle", activities: ["Galle Fort tour", "Cooking class", "Spa experience", "Sunset cocktails"], accommodation: "Amangalla" },
      { day: 10, title: "Departure", description: "Morning you'll head to the airport for your flight home, taking memories of tea-scented highlands and palm-fringed beaches with you.", image: "/images/tours/tea-coastal/departure.jpg", location: "Colombo Airport", activities: ["Airport transfer", "Departure"] },
    ],
  },
];

const dayTours = [
  {
    id: "colombo-city-tour",
    name: "Private Day Tour in Colombo",
    location: "Colombo",
    summary: "Explore the vibrant commercial capital of Sri Lanka with its colorful history running back to the fifth century.",
    overview: "Colombo has a colorful history running back to fifth century. Even in the ancient times this was an important port city in East-West sea trade. Now it has bloomed into a bustling modern city with a unique atmosphere. The spectacular city of Colombo is a mixture of colonial and modern atmosphere. Along with colonial era mansions there are modern condos reaching the sky. The temples architecture demonstrates an eclectic mix of Sri Lankan, Thai, Indian, and Chinese influences.",
    highlights: ["Kelaniya Ancient Temple", "Cultural Exploration (Buddhist, Hindu, Muslim, Christian)", "Independence Square", "Galle Face Green", "Pettah and Port Area", "Fort (Railway Station)", "Shopping Excursion"],
    heroImage: "/images/day-tours/colombo/buddha-reflection.jpg",
    galleryImages: ["/images/day-tours/colombo/buddha-reflection.jpg", "/images/day-tours/colombo/elephants-herd.jpg", "/images/day-tours/colombo/sigiriya-sunset.jpg"],
    duration: "1 Day",
    startsEnds: "Negombo / Colombo",
    tourType: "Private",
    itinerary: [
      { title: "Morning Pickup & Kelaniya Temple", description: "You will be picked up from your hotel in Colombo at 9 am and then proceed to Kelaniya Temple, one of the most sacred Buddhist temples in Sri Lanka." },
      { title: "Galle Face & Gangaramaya Temple", description: "Visit Galle Face Green and Gangaramaya Temple, one of the most important Buddhist temples in Sri Lanka with its unique eclectic architecture." },
      { title: "Fort & Independence Square", description: "Explore the harbor and fort areas of Colombo and visit the Independence Square located just a few minutes away from the Old Parliament building." },
      { title: "Shopping & Return", description: "After lunch, enjoy shopping for high quality clothes at affordable prices. Sri Lanka is known for its garment industry. Return to your hotel." },
    ],
    inclusions: ["Transportation by A/C vehicle", "Pick up to drop off at airport/hotel", "English speaking chauffeur guide", "All entrance tickets at mentioned sites", "Portage & service charge"],
    exclusions: ["Lunch throughout the tour", "Expenses of a personal nature", "Telephone calls, laundry, beverages"],
    tags: ["culture", "city", "heritage"],
  },
  {
    id: "kandy-day-tour",
    name: "Private Day Tour to Kandy",
    location: "Kandy",
    summary: "Visit the UNESCO World Heritage city of Kandy, the last capital of the ancient kings era with the sacred Temple of the Tooth.",
    overview: "Kandy is a major city in Sri Lanka, located in the Central Province. It was the last capital of the ancient kings era of Sri Lanka. The city lies in the midst of hills in the Kandy plateau, which crosses an area of tropical plantations, mainly tea. Kandy is home of The Temple of the Tooth Relic (Sri Dalada Maligawa), one of the most sacred places of worship in the Buddhist world. It was declared a World Heritage Site by UNESCO in 1988.",
    highlights: ["Peradeniya Botanical Garden", "Temple of Tooth Relic", "Kandy City / Kandy Lake", "Bahirawakanda Temple", "Cultural Dance Show"],
    heroImage: "/images/day-tours/kandy/buddha-reflection.jpg",
    galleryImages: ["/images/day-tours/kandy/buddha-reflection.jpg", "/images/day-tours/kandy/tea-plantation-aerial.jpg", "/images/day-tours/kandy/tropical-waterfall.jpg"],
    duration: "1 Day",
    startsEnds: "Negombo / Colombo",
    tourType: "Private",
    itinerary: [
      { title: "Peradeniya Botanical Gardens", description: "Leave Colombo at 6:30 am and drive 3 hours to Peradeniya, home of the Royal Botanical Garden with its large collection of ornamental, decorative, and medicinal plants, as well as orchids." },
      { title: "Kandy City Exploration", description: "Pause for lunch before continuing to Kandy. Shop for unique souvenirs including silk, crafts, gems, and batiks. Visit the Kandy View Point and Bahirawakanda Temple." },
      { title: "Temple of the Tooth", description: "Visit the Temple of the Tooth, a holy Buddhist temple that draws pilgrims from all over the world. According to legend, the temple holds a relic of the tooth of Buddha." },
      { title: "Return Journey", description: "Leave Kandy en route to Colombo, stopping in Ambepussa for dinner. Return to your hotel around 11 pm." },
    ],
    inclusions: ["Transportation by A/C vehicle", "Pick up to drop off at airport/hotel", "English speaking chauffeur guide", "All entrance tickets at mentioned sites", "Portage & service charge"],
    exclusions: ["Lunch throughout the tour", "Expenses of a personal nature", "Telephone calls, laundry, beverages"],
    tags: ["culture", "religion", "nature"],
  },
  {
    id: "galle-day-tour",
    name: "Private Day Tour to Galle",
    location: "Galle",
    summary: "Discover the UNESCO World Heritage Galle Fort, a Portuguese-built fortress with Dutch fortifications and rich colonial history.",
    overview: "Galle is a major city situated on the southwestern tip of Sri Lanka. The Galle Fort is a World Heritage Site and the largest remaining fortress in Asia built by European occupiers. Galle is the best example of a fortified city built by the Portuguese in South and Southeast Asia. Other landmarks include the natural harbor, National Maritime Museum, St. Marys Cathedral, and the historic Amangalla luxury hotel.",
    highlights: ["Kosgoda Sea Turtle Hatchery", "Madu River Boat Ride", "Batik Factory", "Hand Made Lace (Beeralu)", "Traditional Mask Factory", "Dutch Galle Fort", "Stilt Fishermen"],
    heroImage: "/images/day-tours/galle/kalpitiya-beach-sunset.jpg",
    galleryImages: ["/images/day-tours/galle/kalpitiya-beach-sunset.jpg", "/images/day-tours/galle/surfing-waves.jpg", "/images/day-tours/galle/snorkeling-reef.jpg"],
    duration: "1 Day",
    startsEnds: "Negombo / Colombo",
    tourType: "Private",
    itinerary: [
      { title: "Kosgoda Turtle Hatchery", description: "Meet your guide at 7 am for a 12-hour day tour. Begin at the Kosgoda Turtle Hatchery, home to seven species of marine turtles and other wild sea life." },
      { title: "Madu River Boat Ride", description: "Experience a wonderful boat ride at Madu River, a complex wetland ecosystem protected by the Ramsar Convention, containing pristine mangrove forest." },
      { title: "Ambalangoda Crafts", description: "Visit the Mask Factory in Ambalangoda, Batik Factory, and see the traditional Hand Made Lace (Beeralu) crafting." },
      { title: "Galle Fort & Stilt Fishermen", description: "Explore Galle Fort, a Portuguese-built and Dutch-fortified 16th-century fortress. Continue to Weligama to see the famous stilt fishermen. Return to Colombo." },
    ],
    inclusions: ["Transportation by A/C vehicle", "Pick up to drop off at airport/hotel", "English speaking chauffeur guide", "All entrance tickets at mentioned sites", "Portage & service charge"],
    exclusions: ["Lunch throughout the tour", "Expenses of a personal nature", "Telephone calls, laundry, beverages"],
    tags: ["heritage", "beach", "culture"],
  },
  {
    id: "yala-safari-day-tour",
    name: "Private Day Tour to Yala National Park",
    location: "Yala National Park",
    summary: "Experience an exciting wildlife safari at Yala, the most visited national park with the highest leopard density in the world.",
    overview: "Yala National Park is the most visited and second largest national park in Sri Lanka. It is best known for its variety of wild animals and is important for the conservation of Sri Lankan elephants, leopards, and aquatic birds. Yala hosts a variety of ecosystems ranging from moist monsoon forests to freshwater and marine wetlands. It harbours 215 bird species including six endemic species, 44 mammal species, and has one of the highest leopard densities in the world.",
    highlights: ["Sri Lankan Lunch", "Jeep Safari Adventure", "Leopard Spotting", "Elephants & Water Buffalos", "Sloth Bears & Wild Boars", "Spotted Deer & Sambars", "Bird Watching"],
    heroImage: "/images/day-tours/yala/leopard-tree.jpg",
    galleryImages: ["/images/day-tours/yala/leopard-tree.jpg", "/images/day-tours/yala/elephants-herd.jpg", "/images/day-tours/yala/tea-plantation-aerial.jpg"],
    duration: "1 Day",
    startsEnds: "Negombo / Colombo",
    tourType: "Private",
    itinerary: [
      { title: "Leave for Tissamaharama", description: "Early morning at 6:30 am, leave for Tissamaharama (approx. 6 hours drive). Refresh upon arriving and enjoy a Sri Lankan lunch." },
      { title: "Yala National Park Safari", description: "Around 2:30 pm, begin your safari adventure. Spot colorful storks, dozing crocodiles, fan-tailed peacocks, and monkeys. Look for Sloth Bears, Leopards, Elephants, Water Buffalos, Wild Boars, Spotted Deer, Sambars, and Golden Jackals." },
      { title: "Leopard Spotting", description: "If you're lucky, gaze at distinct Sri Lankan leopards. Yala National Park's Block 1 has recorded the highest density of leopards among wildlife parks in Sri Lanka." },
      { title: "Return Journey", description: "After the safari, transfer back to your hotel in Colombo/Negombo, arriving late evening." },
    ],
    inclusions: ["Transportation by A/C vehicle", "Pick up to drop off at airport/hotel", "English speaking chauffeur guide", "All entrance tickets at mentioned sites", "Portage & service charge"],
    exclusions: ["Lunch throughout the tour", "Expenses of a personal nature", "Telephone calls, laundry, beverages"],
    tags: ["wildlife", "safari", "nature"],
  },
  {
    id: "sigiriya-day-tour",
    name: "Private Day Tour to Sigiriya Fortress",
    location: "Sigiriya & Dambulla",
    summary: "Climb the iconic 5th-century Sigiriya Rock Fortress and explore the ancient Dambulla Cave Temple, both UNESCO World Heritage Sites.",
    overview: "Sigiriya is an ancient palace located in the central Matale District. This site was selected by King Kasyapa (477-495 CE) for his new capital. He built his palace on the top of this rock nearly 200 meters high and decorated its sides with colorful frescoes. The name derives from Sihagiri, the Lion Rock, due to the enormous lion gateway. Today Sigiriya is a UNESCO World Heritage Site and one of the best preserved examples of ancient urban planning. It is the most visited historic site in Sri Lanka.",
    highlights: ["Sigiriya Rock Fortress", "Water Gardens", "Boulder Gardens", "Terraced Gardens", "Mirror Wall", "Ancient Frescoes", "Dambulla Cave Temple"],
    heroImage: "/images/day-tours/sigiriya/sigiriya-sunset.jpg",
    galleryImages: ["/images/day-tours/sigiriya/sigiriya-sunset.jpg", "/images/day-tours/sigiriya/buddha-reflection.jpg", "/images/day-tours/sigiriya/tea-plantation-aerial.jpg"],
    duration: "1 Day",
    startsEnds: "Negombo / Colombo",
    tourType: "Private",
    itinerary: [
      { title: "Sigiriya Rock Fortress", description: "Early morning at 6:30 am, leave for Sigiriya (approx. 4 hours drive) and climb the 5th-century Sigiriya rock fortress. Famous for its toadstool of golden-hued granite protruding into the blue sky from a wilderness transformed in rainy season to a water garden." },
      { title: "Explore the Ancient Palace", description: "Discover the water gardens, boulder gardens, terraced gardens, the famous Mirror Wall with ancient graffiti, and the stunning frescoes of celestial maidens." },
      { title: "Dambulla Cave Temple", description: "After lunch, visit Dambulla rock temple built by King Walagambahu in the 1st century BC. This World Heritage Site has five caves with over 2000 sq. meters of painted walls and ceilings, containing over 150 Buddha images." },
      { title: "Return to Hotel", description: "On completion of this visit, you will be driven back to your hotel in Colombo/Negombo." },
    ],
    inclusions: ["Transportation by A/C vehicle", "Pick up to drop off at airport/hotel", "English speaking chauffeur guide", "All entrance tickets at mentioned sites", "Portage & service charge"],
    exclusions: ["Lunch throughout the tour", "Expenses of a personal nature", "Telephone calls, laundry, beverages"],
    tags: ["culture", "heritage", "UNESCO"],
  },
  {
    id: "kitulgala-rafting-tour",
    name: "Private White Water Rafting Day Tour",
    location: "Kitulgala",
    summary: "Experience thrilling white water rafting adventure on the Kelani River in the picturesque wet zone rain forest of Kitulgala.",
    overview: "Kitulgala is a small town in the west of Sri Lanka in the wet zone rain forest. It is one of the wettest places in the country. The Academy Award-winning \"The Bridge on the River Kwai\" was filmed on the Kelani River near Kitulgala. Kitulgala is a base for white water rafting which starts a few kilometers upstream. Large numbers of people visit to enjoy the beautiful scenery, play in the river, and have excellent rice and curry lunch.",
    highlights: ["White Water Rafting in Kelani River", "Flat Water Rafting for Kids", "Jungle Walks to Waterfalls", "Mountain Biking", "River Bathing", "Waterfall Jumps & Abseiling", "Bird Watching"],
    heroImage: "/images/day-tours/kitulgala/tropical-waterfall.jpg",
    galleryImages: ["/images/day-tours/kitulgala/tropical-waterfall.jpg", "/images/day-tours/kitulgala/tea-plantation-aerial.jpg", "/images/day-tours/kitulgala/train-scenic.jpg"],
    duration: "1 Day",
    startsEnds: "Negombo / Colombo",
    tourType: "Private",
    itinerary: [
      { title: "Drive to Kitulgala", description: "Get out of the city and take a 2-hour drive to Kitulgala from Colombo via the Nuwara Eliya road through beautiful scenery." },
      { title: "Safety Briefing", description: "Receive a comprehensive safety briefing from experienced instructors before your rafting adventure begins." },
      { title: "White Water Rafting Adventure", description: "Hop in your white water raft and head out on the Kelani River for an adrenaline-filled adventure through rapids surrounded by lush rainforest." },
      { title: "Lunch & Return", description: "Enjoy a traditional Sri Lankan rice and curry lunch at Kitulgala. In the evening, transfer back to your hotel in Colombo." },
    ],
    inclusions: ["Transportation by A/C vehicle", "Pick up to drop off at airport/hotel", "English speaking chauffeur guide", "White water rafting equipment & guide", "Portage & service charge"],
    exclusions: ["Lunch throughout the tour", "Expenses of a personal nature", "Telephone calls, laundry, beverages"],
    tags: ["adventure", "nature", "rafting"],
  },
];

export async function POST(request: NextRequest) {
  const user = await verifyAuth(request);
  if (!user) return unauthorizedResponse();
  if (!isSuperAdmin(user.email)) return forbiddenResponse();

  try {
    const now = new Date().toISOString();
    const batch = adminDb.batch();
    let tourCount = 0;
    let dayTourCount = 0;

    for (const tour of tours) {
      const docRef = adminDb.collection("tours").doc(tour.id);
      batch.set(docRef, {
        ...tour,
        published: true,
        createdAt: now,
        updatedAt: now,
      });
      tourCount++;
    }

    for (const dayTour of dayTours) {
      const docRef = adminDb.collection("dayTours").doc(dayTour.id);
      batch.set(docRef, {
        ...dayTour,
        published: true,
        createdAt: now,
        updatedAt: now,
      });
      dayTourCount++;
    }

    await batch.commit();

    return Response.json({
      message: "Database seeded successfully",
      toursInserted: tourCount,
      dayToursInserted: dayTourCount,
    });
  } catch (error) {
    console.error("Error seeding database:", error);
    return Response.json({ error: "Failed to seed database" }, { status: 500 });
  }
}
